export const MOBILE_BREAK_POINT = 650;
export const TABLET_BREAK_POINT = 800;

export const VERTICAL_HEIGHT = 490;
export const HORIZONTAL_HEIGHT = 520;
export const VERTICAL_EXCHANGES_WIDTH = 168;
export const VERTICAL_CURRENCY_WIDTH = 66;

export const TABLET_EXCHANGES_WIDTH = 136;

export const HORIZONTAL_CURRENCY_WIDTH = 52;
export const HORIZONTAL_EXCHANGES_HEIGHT = 93;
export const SELECT_COLUMN_WIDTH = 50;
export const SELECTED_EXCHANGE_WIDTH = 184;
export const TABLET_SELECTED_EXCHANGE_WIDTH = 160;

export const SELECTED_CURRENCY_WIDTH = 260;
export const SELECTED_CURRENCY_HEIGHT = 332;
export const SELECTED_CURRENCY_HEIGHT_SUCCESS = 356;
export const HORIZONTAL_SELECTED_CURRENCY_HEIGHT = 258;
